name: lunasea
description: Self Hosted Manager
version: 3.0.0+300100
publish_to: 'none'
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  convert: ^2.1.1
  cupertino_icons: ^0.1.3
  dio: ^3.0.9
  encrypt: ^4.0.2
  expandable: ^4.1.4
  file_picker: ^1.9.0+1
  flare_flutter: ^2.0.3
  flash: ^1.3.1
  flutter:
    sdk: flutter
  flutter_advanced_networkimage: ^0.7.0
  flutter_sticky_header: ^0.4.2
  flutter_svg: ^0.17.4
  f_logs: ^1.2.2
  google_fonts: ^1.1.0
  google_nav_bar: ^2.2.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  in_app_purchase: ^0.3.4
  intl: ^0.16.1
  package_info: ^0.4.0+18
  path_provider: ^1.6.9
  percent_indicator: ^2.1.3
  permission_handler: ^4.4.0+hotfix.2
  provider: ^4.1.2
  stack_trace: ^1.9.3
  table_calendar: ^2.2.3
  tuple: ^1.0.3
  url_launcher: ^5.4.10
  validators: ^2.0.0+1
  xml_parser: ^0.1.2

dev_dependencies:
  build_runner: ^1.10.0
  dapackages: ^1.1.1
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  hive_generator: ^0.7.0+2

flutter:
  uses-material-design: true
  assets:
    # Colors
    - assets/images/colors/accent.png
    - assets/images/colors/black.png
    - assets/images/colors/secondary.png
    # No Poster/Art Available
    - assets/images/lidarr/noalbumart.png
    - assets/images/lidarr/noartistposter.png
    - assets/images/radarr/nomovieposter.png
    - assets/images/sonarr/noseriesposter.png
    # Services
    - assets/images/services/imdb.png
    - assets/images/services/youtube.png
    - assets/images/services/tvmaze.png
    - assets/images/services/thetvdb.png
    - assets/images/services/themoviedb.png
    - assets/images/services/discogs.png
    - assets/images/services/bandsintown.png
    - assets/images/services/lastfm.png
    # Branding
    - assets/branding/icon.png
    # Rive Animations
    - assets/rive/coding.flr
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/CustomIcons.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/branding/icon.png"
  adaptive_icon_background: "#32323E"
  adaptive_icon_foreground: "assets/branding/icon_adaptive.png"

flutter_native_splash:
  image: "assets/branding/splash.png"
  color: "#32323E"
