name: trendy_whatsapp_stickers
description: Complete WhatsApp sticker App using Flutter.
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_whatsapp_stickers:
  firebase_admob: ^0.5.5
  url_launcher:
  esys_flutter_share: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - sticker_packs/1/
    - sticker_packs/2/
    - sticker_packs/3/
    - sticker_packs/4/
    - sticker_packs/5/
    - sticker_packs/6/
    - sticker_packs/7/
    - sticker_packs/sticker_packs.json
